version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ecoride_web
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: ecoride_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride_db
      MYSQL_USER: ecoride
      MYSQL_PASSWORD: ecoride
    ports:
      - "3307:3306"
    volumes:
      - ecoride_db_data:/var/lib/mysql

volumes:
  ecoride_db_data:
